package stateless

import (
	"time"

	"github.com/ipfs-cluster/ipfs-cluster/config"
)

const configKey = "stateless"
const envConfigKey = "cluster_stateless"

// Default values for this Config.
const (
	DefaultMaxPinQueueSize       = 1000000
	DefaultConcurrentPins        = 10
	DefaultPriorityPinMaxAge     = 24 * time.Hour
	DefaultPriorityPinMaxRetries = 5
)

// Config allows to initialize a Monitor and customize some parameters.
type Config struct {
	config.Saver

	// If higher, they will automatically marked with an error.
	MaxPinQueueSize int
	// ConcurrentPins specifies how many pin requests can be sent to the ipfs
	// daemon in parallel. If the pinning method is "refs", it might increase
	// speed. Unpin requests are always processed one by one.
	ConcurrentPins int

	// PriorityPinMaxAge specifies the maximum age that a pin needs to
	// can have since it was submitted to the cluster to be pinned
	// preferentially (before pins that are older or have too many retries).
	PriorityPinMaxAge time.Duration

	// PriorityPinMaxRetries specifies the maximum amount of retries that
	// a pin can have before it is moved to a non-prioritary queue.
	PriorityPinMaxRetries int
}

type jsonConfig struct {
	MaxPinQueueSize       int    `json:"max_pin_queue_size,omitempty"`
	ConcurrentPins        int    `json:"concurrent_pins"`
	PriorityPinMaxAge     string `json:"priority_pin_max_age"`
	PriorityPinMaxRetries int    `json:"priority_pin_max_retries"`
}

// ConfigKey provides a human-friendly identifier for this type of Config.
func (cfg *Config) ConfigKey() string {
	_ = "STUB: not implemented"

	// Default sets the fields of this Config to sensible values.
	return ""
}

func (cfg *Config) Default() error { _ = "STUB: not implemented"; return nil }

// ApplyEnvVars fills in any Config fields found
// as environment variables.
func (cfg *Config) ApplyEnvVars() error { _ = "STUB: not implemented"; return nil }

// Validate checks that the fields of this Config have working values,
// at least in appearance.
func (cfg *Config) Validate() error { _ = "STUB: not implemented"; return nil }

// LoadJSON sets the fields of this Config to the values defined by the JSON
// representation of it, as generated by ToJSON.
func (cfg *Config) LoadJSON(raw []byte) error { _ = "STUB: not implemented"; return nil }

func (cfg *Config) applyJSONConfig(jcfg *jsonConfig) error { _ = "STUB: not implemented"; return nil }

// ToJSON generates a human-friendly JSON representation of this Config.
func (cfg *Config) ToJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (cfg *Config) toJSONConfig() *jsonConfig { _ = "STUB: not implemented"; return nil }

// ToDisplayJSON returns JSON config as a string.
func (cfg *Config) ToDisplayJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
