package config

import (
	crypto "github.com/libp2p/go-libp2p/core/crypto"
	peer "github.com/libp2p/go-libp2p/core/peer"
)

const configKey = "cluster"

// Identity defaults
const (
	DefaultConfigCrypto    = crypto.Ed25519
	DefaultConfigKeyLength = -1
)

// Identity represents identity of a cluster peer for communication,
// including the Consensus component.
type Identity struct {
	ID         peer.ID
	PrivateKey crypto.PrivKey
}

// identityJSON represents a Cluster peer identity as it will look when it is
// saved using JSON.
type identityJSON struct {
	ID         string `json:"id"`
	PrivateKey string `json:"private_key"`
}

// NewIdentity returns a new random identity.
func NewIdentity() (*Identity, error) { _ = "STUB: not implemented"; return nil, nil }

// Default generates a random keypair for this identity.
func (ident *Identity) Default() error {
	_ = "STUB: not implemented"
	// pid and private key generation
	return nil
}

// ConfigKey returns a human-readable string to identify
// a cluster Identity.
func (ident *Identity) ConfigKey() string {
	_ = "STUB: not implemented"

	// SaveJSON saves the JSON representation of the Identity to
	// the given path.
	return ""
}

func (ident *Identity) SaveJSON(path string) error { _ = "STUB: not implemented"; return nil }

// ToJSON generates a human-friendly version of Identity.
func (ident *Identity) ToJSON() (raw []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (ident *Identity) toIdentityJSON() (jID *identityJSON, err error) {
	_ = "STUB: not implemented"
	return nil,

		// Private Key
		nil
}

// Set all identity fields

// LoadJSON receives a raw json-formatted identity and
// sets the Config fields from it. Note that it should be JSON
// as generated by ToJSON().
func (ident *Identity) LoadJSON(raw []byte) error { _ = "STUB: not implemented"; return nil }

func (ident *Identity) applyIdentityJSON(jID *identityJSON) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate will check that the values of this identity
// seem to be working ones.
func (ident *Identity) Validate() error { _ = "STUB: not implemented"; return nil }

// LoadJSONFromFile reads an Identity file from disk and parses
// it and return Identity.
func (ident *Identity) LoadJSONFromFile(path string) error { _ = "STUB: not implemented"; return nil }

// ApplyEnvVars fills in any Config fields found
// as environment variables.
func (ident *Identity) ApplyEnvVars() error { _ = "STUB: not implemented"; return nil }

// Equals returns true if equal to provided identity.
func (ident *Identity) Equals(i *Identity) bool { _ = "STUB: not implemented"; return false }
