package numpin

import (
	"time"

	"github.com/ipfs-cluster/ipfs-cluster/config"
)

const configKey = "numpin"
const envConfigKey = "cluster_numpin"

// These are the default values for a Config.
const (
	DefaultMetricTTL = 10 * time.Second
)

// Config allows to initialize an Informer.
type Config struct {
	config.Saver

	MetricTTL time.Duration
}

type jsonConfig struct {
	MetricTTL string `json:"metric_ttl"`
}

// ConfigKey returns a human-friendly identifier for this
// Config's type.
func (cfg *Config) ConfigKey() string {
	_ = "STUB: not implemented"

	// Default initializes this Config with sensible values.
	return ""
}

func (cfg *Config) Default() error { _ = "STUB: not implemented"; return nil }

// ApplyEnvVars fills in any Config fields found
// as environment variables.
func (cfg *Config) ApplyEnvVars() error { _ = "STUB: not implemented"; return nil }

// Validate checks that the fields of this configuration have
// sensible values.
func (cfg *Config) Validate() error { _ = "STUB: not implemented"; return nil }

// LoadJSON parses a raw JSON byte-slice as generated by ToJSON().
func (cfg *Config) LoadJSON(raw []byte) error { _ = "STUB: not implemented"; return nil }

func (cfg *Config) applyJSONConfig(jcfg *jsonConfig) error { _ = "STUB: not implemented"; return nil }

// ToJSON generates a human-friendly JSON representation of this Config.
func (cfg *Config) ToJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (cfg *Config) toJSONConfig() *jsonConfig { _ = "STUB: not implemented"; return nil }

// ToDisplayJSON returns JSON config as a string.
func (cfg *Config) ToDisplayJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
