package badger

import (
	"time"

	"github.com/dgraph-io/badger"
	"github.com/dgraph-io/badger/options"

	"github.com/ipfs-cluster/ipfs-cluster/config"
)

const configKey = "badger"
const envConfigKey = "cluster_badger"

// Default values for badger Config
const (
	DefaultSubFolder = "badger"
)

var (
	// DefaultBadgerOptions has to be a var because badger.DefaultOptions
	// is. Values are customized during Init().
	DefaultBadgerOptions badger.Options

	// DefaultGCDiscardRatio for GC operations. See Badger docs.
	DefaultGCDiscardRatio float64 = 0.2
	// DefaultGCInterval specifies interval between GC cycles.
	DefaultGCInterval time.Duration = 15 * time.Minute
	// DefaultGCSleep specifies sleep time between GC rounds.
	DefaultGCSleep time.Duration = 10 * time.Second
)

func init() {
	// Following go-ds-badger guidance
	DefaultBadgerOptions = badger.DefaultOptions("")
	DefaultBadgerOptions.CompactL0OnClose = false
	DefaultBadgerOptions.Truncate = true
	DefaultBadgerOptions.ValueLogLoadingMode = options.FileIO
	// Explicitly set this to mmap. This doesn't use much memory anyways.
	DefaultBadgerOptions.TableLoadingMode = options.MemoryMap
	// Reduce this from 64MiB to 16MiB. That means badger will hold on to
	// 20MiB by default instead of 80MiB.
	DefaultBadgerOptions.MaxTableSize = 16 << 20
}

// Config is used to initialize a BadgerDB datastore. It implements the
// ComponentConfig interface.
type Config struct {
	config.Saver

	// The folder for this datastore. Non-absolute paths are relative to
	// the base configuration folder.
	Folder string

	// For GC operation. See Badger documentation.
	GCDiscardRatio float64

	// Interval between GC cycles. Each GC cycle runs one or more
	// rounds separated by GCSleep.
	GCInterval time.Duration

	// Time between rounds in a GC cycle
	GCSleep time.Duration

	BadgerOptions badger.Options
}

// badgerOptions is a copy of options.BadgerOptions but
// without the Logger as it cannot be marshaled to/from
// JSON.
type badgerOptions struct {
	Dir                     string                   `json:"dir"`
	ValueDir                string                   `json:"value_dir"`
	SyncWrites              bool                     `json:"sync_writes"`
	TableLoadingMode        *options.FileLoadingMode `json:"table_loading_mode"`
	ValueLogLoadingMode     *options.FileLoadingMode `json:"value_log_loading_mode"`
	NumVersionsToKeep       int                      `json:"num_versions_to_keep"`
	MaxTableSize            int64                    `json:"max_table_size"`
	LevelSizeMultiplier     int                      `json:"level_size_multiplier"`
	MaxLevels               int                      `json:"max_levels"`
	ValueThreshold          int                      `json:"value_threshold"`
	NumMemtables            int                      `json:"num_memtables"`
	NumLevelZeroTables      int                      `json:"num_level_zero_tables"`
	NumLevelZeroTablesStall int                      `json:"num_level_zero_tables_stall"`
	LevelOneSize            int64                    `json:"level_one_size"`
	ValueLogFileSize        int64                    `json:"value_log_file_size"`
	ValueLogMaxEntries      uint32                   `json:"value_log_max_entries"`
	NumCompactors           int                      `json:"num_compactors"`
	CompactL0OnClose        bool                     `json:"compact_l_0_on_close"`
	ReadOnly                bool                     `json:"read_only"`
	Truncate                bool                     `json:"truncate"`
}

func (bo *badgerOptions) Unmarshal() *badger.Options { _ = "STUB: not implemented"; return nil }

func (bo *badgerOptions) Marshal(badgerOpts *badger.Options) { _ = "STUB: not implemented"; return }

type jsonConfig struct {
	Folder         string        `json:"folder,omitempty"`
	GCDiscardRatio float64       `json:"gc_discard_ratio"`
	GCInterval     string        `json:"gc_interval"`
	GCSleep        string        `json:"gc_sleep"`
	BadgerOptions  badgerOptions `json:"badger_options,omitempty"`
}

// ConfigKey returns a human-friendly identifier for this type of Datastore.
func (cfg *Config) ConfigKey() string {
	_ = "STUB: not implemented"

	// Default initializes this Config with sensible values.
	return ""
}

func (cfg *Config) Default() error { _ = "STUB: not implemented"; return nil }

// ApplyEnvVars fills in any Config fields found as environment variables.
func (cfg *Config) ApplyEnvVars() error { _ = "STUB: not implemented"; return nil }

// Validate checks that the fields of this Config have working values,
// at least in appearance.
func (cfg *Config) Validate() error { _ = "STUB: not implemented"; return nil }

// LoadJSON reads the fields of this Config from a JSON byteslice as
// generated by ToJSON.
func (cfg *Config) LoadJSON(raw []byte) error { _ = "STUB: not implemented"; return nil }

func (cfg *Config) applyJSONConfig(jcfg *jsonConfig) error { _ = "STUB: not implemented"; return nil }

// 0 is an invalid option anyways. In that case, set default (0.2)

// If these durations are set, GC is enabled by default with default
// values.

// ToJSON generates a JSON-formatted human-friendly representation of this
// Config.
func (cfg *Config) ToJSON() (raw []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (cfg *Config) toJSONConfig() *jsonConfig { _ = "STUB: not implemented"; return nil }

// GetFolder returns the BadgerDB folder.
func (cfg *Config) GetFolder() string { _ = "STUB: not implemented"; return "" }

// ToDisplayJSON returns JSON config as a string.
func (cfg *Config) ToDisplayJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
