// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package optracker

const _OperationType_name = "OperationUnknownOperationPinOperationUnpinOperationRemoteOperationShard"

var _OperationType_index = [...]uint8{0, 16, 28, 42, 57, 71}

func (i OperationType) String() string { _ = "STUB: not implemented"; return "" }
