// Code generated by "stringer -type=Phase"; DO NOT EDIT.

package optracker

const _Phase_name = "PhaseErrorPhaseQueuedPhaseInProgressPhaseDone"

var _Phase_index = [...]uint8{0, 10, 21, 36, 45}

func (i Phase) String() string { _ = "STUB: not implemented"; return "" }
