package balanced

import (
	"github.com/ipfs-cluster/ipfs-cluster/config"
)

const configKey = "balanced"
const envConfigKey = "cluster_balanced"

// These are the default values for a Config.
var (
	DefaultAllocateBy = []string{"tag:group", "freespace"}
)

// Config allows to initialize the Allocator.
type Config struct {
	config.Saver

	AllocateBy []string
}

type jsonConfig struct {
	AllocateBy []string `json:"allocate_by"`
}

// ConfigKey returns a human-friendly identifier for this
// Config's type.
func (cfg *Config) ConfigKey() string {
	_ = "STUB: not implemented"

	// Default initializes this Config with sensible values.
	return ""
}

func (cfg *Config) Default() error { _ = "STUB: not implemented"; return nil }

// ApplyEnvVars fills in any Config fields found
// as environment variables.
func (cfg *Config) ApplyEnvVars() error { _ = "STUB: not implemented"; return nil }

// Validate checks that the fields of this configuration have
// sensible values.
func (cfg *Config) Validate() error { _ = "STUB: not implemented"; return nil }

// LoadJSON parses a raw JSON byte-slice as generated by ToJSON().
func (cfg *Config) LoadJSON(raw []byte) error { _ = "STUB: not implemented"; return nil }

func (cfg *Config) applyJSONConfig(jcfg *jsonConfig) error {
	_ = "STUB: not implemented"
	// When unset, leave default
	return nil
}

// ToJSON generates a human-friendly JSON representation of this Config.
func (cfg *Config) ToJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (cfg *Config) toJSONConfig() *jsonConfig { _ = "STUB: not implemented"; return nil }

// ToDisplayJSON returns JSON config as a string.
func (cfg *Config) ToDisplayJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }
